import Link from "next/link";
import { ArrowRight, ArrowUpRight, Flame, Globe2, Leaf, ShieldCheck, Truck, type LucideIcon } from "lucide-react";
import type { Metadata } from "next";
import { CategoryCard } from "@/components/public/CategoryCard";
import { CertificateCard } from "@/components/public/CertificateCard";
import { ProductCard } from "@/components/public/ProductCard";
import { ProductImage } from "@/components/public/ProductImage";
import { SectionHeader } from "@/components/public/SectionHeader";
import { isDemoMode } from "@/lib/demo";
import { localizeCompany, localizeHomepage, localizeProduct, localizeProject, localizeSiteSettings } from "@/lib/i18n/content";
import { localeConfig, localePath, type Locale } from "@/lib/i18n/config";
import { getDictionary } from "@/lib/i18n/dictionary";
import { buildLocalizedMetadata } from "@/lib/i18n/metadata";
import { getMockFeaturedProducts, mockCategories, mockCertificates, mockCompany } from "@/lib/mock-data";
import { fetchHomepageContent, fetchSiteSettings } from "@/lib/queries/cms";
import { createPublicSupabaseClient } from "@/lib/supabase/public";
import { serializeJsonLd, siteUrl } from "@/lib/utils";
import { safeAddress, safeEmail, safePhone, sanitizeCompany } from "@/lib/content/placeholder-detection";
import type { Category, Certificate, CompanyProfile, HomeFeatureItem, Product, Project } from "@/types/database";
import { getFeaturedProjects } from "@/lib/repositories/projects";

export const publicHomeRevalidate = 300;
const featureIcons: Record<string, LucideIcon> = { flame: Flame, leaf: Leaf, truck: Truck, globe: Globe2, shield: ShieldCheck };
const fallbackFeatures: Record<Locale, HomeFeatureItem[]> = {
  zh: [{ icon: "flame", title: "B 级防火", description: "具体等级以产品详情与公开检测资料为准" }, { icon: "leaf", title: "E0 环保", description: "适用于室内工程与装饰应用" }, { icon: "truck", title: "工程交付", description: "支持工程批量供货与规格定制" }, { icon: "globe", title: "海外采购", description: "支持多语言询盘与 FOB/CIF 出口" }],
  en: [{ icon: "flame", title: "B Fire Rating", description: "Refer to product details and published test documents." }, { icon: "leaf", title: "E0 Grade", description: "For indoor project and decorative applications." }, { icon: "truck", title: "Project Supply", description: "Bulk project supply and custom specifications." }, { icon: "globe", title: "Overseas Inquiry", description: "Multilingual inquiries and FOB/CIF export support." }],
};

export async function getHomeMetadata(locale: Locale): Promise<Metadata> { const settings = localizeSiteSettings(await fetchSiteSettings(), locale); const copy = getDictionary(locale).home; return buildLocalizedMetadata({ locale, path: "/", title: settings.metaTitle || `KZQ | ${copy.heroTitle}`, description: settings.metaDescription || copy.heroDescription, absolute: true }); }
export function generateMetadata() { return getHomeMetadata("zh"); }

export async function HomePageContent(locale: Locale) {
  let featuredProducts: Product[] = []; let categories: Category[] = []; let certificates: Certificate[] = []; let company: CompanyProfile | null = null;
  if (isDemoMode()) { featuredProducts = getMockFeaturedProducts(8); categories = [...mockCategories].sort((a, b) => a.sort_order - b.sort_order); certificates = mockCertificates.filter((item) => item.is_published).sort((a, b) => a.sort_order - b.sort_order).slice(0, 3); company = sanitizeCompany(mockCompany); }
  else { const supabase = createPublicSupabaseClient(); const [productsResult, categoryResult, certificateResult, companyResult] = await Promise.all([supabase.from("products").select("*").eq("is_published", true).eq("is_featured", true).order("sort_order", { ascending: true }).limit(8), supabase.from("categories").select("*").eq("is_active", true).order("sort_order", { ascending: true }), supabase.from("certificates").select("*").eq("is_published", true).order("sort_order", { ascending: true }).limit(3), supabase.from("company_profile").select("*").limit(1).maybeSingle()]); const queryError = productsResult.error || categoryResult.error || certificateResult.error || companyResult.error; if (queryError) throw new Error("PUBLIC_DATA_UNAVAILABLE", { cause: queryError }); featuredProducts = (productsResult.data as Product[] | null) || []; categories = (categoryResult.data as Category[] | null) || []; certificates = (certificateResult.data as Certificate[] | null) || []; company = sanitizeCompany(companyResult.data as CompanyProfile | null); }
  let featuredProjects: Project[] = [];
  try {
    featuredProjects = await getFeaturedProjects(3);
  } catch (error) {
    console.error("Optional featured projects query failed:", error instanceof Error ? error.message : "unknown error");
  }
  const home = localizeHomepage(await fetchHomepageContent(), locale); const localizedCompany = localizeCompany(company, locale); const copy = getDictionary(locale).home; const heroProduct = featuredProducts[0]; const hero = heroProduct ? localizeProduct(heroProduct, locale) : null;
  const trustItems = home.features.length ? home.features : localizedCompany.advantages.length ? localizedCompany.advantages : fallbackFeatures[locale];
  const organization = { "@context": "https://schema.org", "@type": "Organization", name: "KZQ", url: siteUrl(localePath(locale)), logo: company?.logo_url || undefined, description: localizedCompany.description || undefined, inLanguage: localeConfig[locale].htmlLang, address: safeAddress(localizedCompany.address) ? { "@type": "PostalAddress", streetAddress: safeAddress(localizedCompany.address) } : undefined, contactPoint: { "@type": "ContactPoint", telephone: safePhone(company?.phone) || undefined, email: safeEmail(company?.email) || undefined, contactType: "sales" } };
  return (
    <div className="bg-canvas text-ink">
      <section className="relative isolate min-h-[340px] overflow-hidden bg-page md:min-h-[460px]"><div className="absolute inset-0"><ProductImage src={heroProduct?.cover_image_url} alt={hero?.name || "KZQ"} loading="eager" sizes="100vw" className="scale-[1.02] brightness-[0.52] saturate-[0.72]" /></div><div className="absolute inset-0 bg-[linear-gradient(90deg,rgba(13,15,16,0.96)_0%,rgba(13,15,16,0.83)_42%,rgba(13,15,16,0.34)_100%)]" /><div className="container-responsive relative flex min-h-[340px] items-center py-8 md:min-h-[460px] md:py-12"><div className="max-w-[650px]"><div className="flex items-center gap-3 text-gold-light"><span className="h-px w-10 bg-gold" /><p className="text-[10px] font-medium uppercase tracking-[0.24em] md:text-xs">{home.heroEyebrow || "Engineering Boards · Decorative Panels"}</p></div><h1 className="mt-4 max-w-[640px] text-[29px] font-semibold leading-[1.08] tracking-[-0.03em] text-white md:mt-5 md:text-[48px]">{home.heroTitle || copy.heroTitle}<span className="mt-1 block text-white/[0.72]">{home.heroHighlight || copy.heroHighlight}</span></h1><p className="mt-4 max-w-lg text-[12px] leading-6 text-white/[0.64] md:text-[15px]">{home.heroDescription || copy.heroDescription}</p><div className="mt-5 flex gap-3 md:mt-7"><Link href={localePath(locale, "/products")} className="btn-primary h-11 px-5 text-xs md:h-12 md:text-sm">{home.primaryCta || copy.browse}<ArrowRight className="h-4 w-4" /></Link><Link href={localePath(locale, "/contact")} className="inline-flex h-11 items-center justify-center gap-2 rounded-md border border-white/30 px-5 text-xs font-medium text-white md:h-12 md:text-sm">{home.secondaryCta || copy.inquiry}<ArrowUpRight className="h-4 w-4" /></Link></div></div></div></section>
      <section className="border-b border-ink-line bg-canvas-warm md:hidden"><div className="grid grid-cols-4 divide-x divide-ink-line px-2 py-4">{trustItems.slice(0, 4).map((item, index) => { const Icon = featureIcons[item.icon] || ShieldCheck; return <div key={`${item.title}-${index}`} className="flex min-w-0 flex-col items-center px-1 text-center"><Icon className="h-4 w-4 text-gold-dark" /><span className="mt-2 line-clamp-2 text-[9px] font-medium text-ink">{item.title}</span></div>; })}</div></section>
      {categories.length > 0 && <section className="bg-canvas py-9 md:py-14"><div className="container-responsive"><SectionHeader title={home.categoryTitle || copy.categoryTitle} subtitle={home.categorySubtitle || copy.categorySubtitle} size="large" /><div className="mt-5 grid grid-cols-2 gap-3 md:mt-7 md:grid-cols-3 md:gap-5">{categories.map((category) => <CategoryCard key={category.id} category={category} locale={locale} />)}</div></div></section>}
      {featuredProducts.length > 0 && <section className="border-y border-ink-line bg-canvas-warm py-9 md:py-14"><div className="container-responsive"><SectionHeader title={home.featuredTitle || copy.featuredTitle} subtitle={home.featuredSubtitle || copy.featuredSubtitle} size="large" /><div className="mt-5 grid grid-cols-2 gap-3 md:mt-7 md:grid-cols-3 md:gap-5 lg:grid-cols-4">{featuredProducts.map((product) => <ProductCard key={product.id} product={product} locale={locale} />)}</div></div></section>}
      {featuredProjects.length > 0 && <section className="bg-canvas py-9 md:py-14"><div className="container-responsive"><SectionHeader title={getDictionary(locale).projects.featured} subtitle={getDictionary(locale).projects.subtitle} action={<Link href={localePath(locale, "/projects")} className="text-xs text-gold-dark">{getDictionary(locale).common.viewAll}</Link>} size="large" /><div className="mt-5 grid gap-4 md:grid-cols-3">{featuredProjects.map((project) => { const content = localizeProject(project, locale); return <Link key={project.id} href={localePath(locale, `/projects/${project.slug}`)} className="card-base group overflow-hidden"><div className="aspect-[16/10] overflow-hidden"><ProductImage src={project.cover_image_url} alt={content.title} sizes="(max-width: 768px) 100vw, 33vw" /></div><div className="p-4"><h3 className="font-semibold text-ink">{content.title}</h3><p className="mt-1 text-[11px] text-ink-mute">{[content.projectType, content.country].filter(Boolean).join(" · ")}</p>{content.summary && <p className="mt-2 line-clamp-2 text-xs leading-5 text-ink-soft">{content.summary}</p>}</div></Link>; })}</div></div></section>}
      <section className="relative overflow-hidden bg-graphite py-11 text-white md:py-16"><div className="container-responsive grid gap-12 lg:grid-cols-2"><div><SectionHeader title={home.featureTitle || copy.trustTitle} subtitle={home.featureSubtitle || copy.trustSubtitle} light size="large" />{localizedCompany.description && <p className="mt-7 text-sm leading-7 text-white/[0.55]">{localizedCompany.description}</p>}<div className="mt-8 grid gap-6 sm:grid-cols-2">{trustItems.slice(0, 4).map((item, index) => { const Icon = featureIcons[item.icon] || ShieldCheck; return <div key={`${item.title}-${index}`} className="border-t border-white/10 pt-5"><div className="flex gap-3"><Icon className="h-5 w-5 shrink-0 text-gold" /><div><h3 className="text-sm font-medium">{item.title}</h3><p className="mt-1.5 text-xs leading-5 text-white/[0.45]">{item.description}</p></div></div></div>; })}</div></div>{certificates.length > 0 && <div><h2 className="text-xl font-semibold">{copy.certificates}</h2><div className="no-scrollbar mt-6 flex gap-3 overflow-x-auto">{certificates.map((certificate) => <div key={certificate.id} className="w-[42vw] shrink-0 sm:w-1/3"><CertificateCard cert={certificate} variant="compact" locale={locale} /></div>)}</div><p className="mt-4 text-[10px] leading-5 text-white/[0.35]">{copy.certificateNote}</p></div>}</div></section>
      <section className="bg-canvas py-9 md:py-14"><div className="container-responsive"><div className="relative overflow-hidden rounded-lg bg-page px-5 py-9 text-white md:px-12 md:py-12"><div className="relative flex flex-col items-start justify-between gap-7 md:flex-row md:items-center"><div><p className="text-[10px] uppercase tracking-[0.22em] text-gold-light">Project inquiry</p><h2 className="mt-3 text-2xl font-semibold md:text-4xl">{home.bottomCtaTitle || copy.ctaTitle}</h2><p className="mt-3 text-sm text-white/50">{home.bottomCtaDescription || copy.ctaDescription}</p></div><Link href={localePath(locale, "/contact")} className="btn-primary h-12 w-full px-7 text-sm md:w-auto">{copy.inquiry}<ArrowRight className="h-4 w-4" /></Link></div></div></div></section>
      <script type="application/ld+json" dangerouslySetInnerHTML={{ __html: serializeJsonLd(organization) }} />
    </div>
  );
}
export default function HomePage() { return HomePageContent("zh"); }
