import type { ProductAsset } from "@/types/database";

const createdAt = "2026-07-01T00:00:00.000Z";

export const mockCatalogAssets: ProductAsset[] = [
  {
    id: "mock-catalog-color-card",
    product_id: null,
    asset_type: "catalog",
    catalog_topic_id: "color-card",
    title_cn: "KZQ 综合色卡",
    title_en: "KZQ Color Card",
    description_cn: "Demo 模式综合色卡预览。",
    description_en: "Demo color-card preview.",
    file_url: "/demo/catalogs/kzq-color-card.svg",
    cover_image_url: "/demo/catalogs/kzq-color-card.svg",
    file_size: null,
    mime_type: "image/svg+xml",
    published_at: "2026-07-01",
    content_hash: "demo-color-card",
    is_published: true,
    sort_order: 10,
    created_at: createdAt,
    updated_at: createdAt,
  },
  {
    id: "mock-catalog-wpc-wall-panel",
    product_id: null,
    asset_type: "catalog",
    catalog_topic_id: "wpc-wall-panel",
    title_cn: "WPC 墙板综合目录",
    title_en: "WPC Wall Panel Catalog",
    description_cn: "Demo 模式墙板系列资料。",
    description_en: "Demo wall-panel catalog.",
    file_url: "/demo/catalogs/wpc-wall-panel.svg",
    cover_image_url: "/demo/catalogs/wpc-wall-panel.svg",
    file_size: null,
    mime_type: "image/svg+xml",
    published_at: "2026-06-15",
    content_hash: "demo-wpc-wall-panel",
    is_published: true,
    sort_order: 20,
    created_at: createdAt,
    updated_at: createdAt,
  },
  {
    id: "mock-catalog-edge-finishing",
    product_id: null,
    asset_type: "installation",
    catalog_topic_id: "edge-finishing",
    title_cn: "格栅墙板收边方案",
    title_en: "Fluted Wall Panel Edge Finishing Solutions",
    description_cn: "Demo 模式收边和节点参考。",
    description_en: "Demo edge-finishing reference.",
    file_url: "/demo/catalogs/edge-finishing.svg",
    cover_image_url: "/demo/catalogs/edge-finishing.svg",
    file_size: null,
    mime_type: "image/svg+xml",
    published_at: "2026-05-20",
    content_hash: "demo-edge-finishing",
    is_published: true,
    sort_order: 30,
    created_at: createdAt,
    updated_at: createdAt,
  },
  {
    id: "mock-catalog-hd-spc-test-pdf",
    product_id: null,
    asset_type: "catalog",
    catalog_topic_id: "hd-spc-catalog",
    title_cn: "HD / SPC 测试样本",
    title_en: "HD / SPC Test Sample",
    description_cn: "自动化测试用 PDF 样本，非生产资料。",
    description_en: "Automated test PDF sample, not production data.",
    file_url: "/demo/catalogs/test-sample.pdf",
    cover_image_url: null,
    file_size: 817,
    mime_type: "application/pdf",
    published_at: "2026-07-15",
    content_hash: "demo-test-pdf",
    is_published: true,
    sort_order: 25,
    created_at: createdAt,
    updated_at: createdAt,
  },
];
